name: Fetch AUR Package (uabea)

on:
  workflow_dispatch:  

permissions:
  contents: write

jobs:
  fetch-aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Clone AUR package (uabea)
        run: |
          # Clone only the latest commit (depth 1) to save time
          git clone --depth 1 https://aur.archlinux.org/uabea.git aur_uabea_temp

      - name: Prepare target folder
        run: |
          rm -rf aur-packages/uabea
          mkdir -p aur-packages/uabea

      - name: Copy AUR files (excluding .git)
        run: |
          cp -r aur_uabea_temp/* aur-packages/uabea/
          cp -r aur_uabea_temp/.[!.]* aur-packages/uabea/ 2>/dev/null || true  # hiden files : .SRCINFO

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add aur-packages/uabea/
          git diff --cached --quiet || git commit -m "Update AUR files for uabea package"
          git push