name: file Downloader in url - ZIP

on:
  workflow_dispatch: 
    inputs:
      url:
        description: "file URL"
        required: true
        type: string
      name:
        description: "File name(Full.*)"
        required: true
        type : string


permissions:
  contents: write    

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Downloading
        run: |
          curl -L -o ${{ github.event.inputs.name }} \
          ${{ github.event.inputs.url }}

      - name: Commit and push if file changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.event.inputs.name }}
          git diff --cached --quiet || git commit -m "${{ github.event.inputs.name }}"
          git push
