name: Github releases downloader

on:
  workflow_dispatch: 
    inputs:
      url:
        description: 'URL to fetch'
        required: true
      filename:
        description: 'Output filename'
        required: false
        default: file1
permissions:
  contents: write    

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download ${{ github.event.inputs.filename }}.zip
        run: |
         mkdir -p github_releases
          curl -L -o github_releases/${{ github.event.inputs.filename }}.zip \
          ${{ github.event.inputs.url }}

      - name: Commit and push if file changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github_releases/${{ github.event.inputs.filename }}.zip
          git diff --cached --quiet || git commit -m "Download ${{ github.event.inputs.filename }}.zip"
          git push